### ISSUE TITLE
Include an explicit license file?

### ISSUE THREAD

**Issue by glasser** [josephg/resolvable#1]
We started using this package recently in our open source project. One of our users was [concerned that this package has no license](https://github.com/apollographql/apollo-server/issues/5167). While you've added `"license": "ISC"` to the package.json, there's no explicit license file or copyright statement (and the ISC license actually says that you need to include the copyright statement). Any chance you can quick throw a LICENSE.md into the repo and publish another version? Otherwise we'll have to find an alternative package or try to reimplement it ourselves in a way that isn't legally problematic.

**Comment by josephg** [comment]
Oh sorry about that - little oversight on my part. I’ll fix that up!

**Comment by josephg** [comment]
I've added a license and republished 📦 resolvable@1.0.1. There are no code changes in this release.
